### ISSUE TITLE
Can you specify a license?

### ISSUE THREAD

**Issue by acolchagoff** [MajorVictory/3DDiceRoller#11]
I want to use this in a project but I want to know what strings are attached. could you pick a license? MIT license would be awesome.

**Comment by MajorVictory** [comment]
I have specified one: https://github.com/MajorVictory/3DDiceRoller/blob/master/LICENSE

**Comment by acolchagoff** [comment]
my bad, I'm dumb, I saw that and read 'unlicensed"
