### ISSUE TITLE
Where is the server code?

### ISSUE THREAD

**Issue by Fell** [MajorVictory/3DDiceRoller#3]
Hi, I wanted to fork this project and build upon it, unfortunately I can't find the server code anywhere. Is is not available?

**Comment by Fell** [comment]
I see. Thanks for letting me know. Me and my group are happy to test the dicex branch once you consider it ready. It seems like you're still currently working on it.

**Comment by chriscook8** [comment]
2nd for wanting to see the server code!

**Comment by dnd-volo** [comment]
3rd! thanks for the feature focus BTW, its amazing.

**Comment by MajorVictory** [comment]
I have published the server code here:
https://github.com/MajorVictory/3DDiceWebsocket
